feat: add remark
also use package.json lint-staged scripts

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,17 +1,10 @@
-#!/bin/sh
+#!/usr/bin/env sh
 . "$(dirname "$0")/_/husky.sh"
 
-npx lint-staged
-
-# Get the changed files
-DIFF_FILES=$(git diff HEAD --name-only '*.md')
-echo $DIFF_FILES
-
-if [ -z "$DIFF_FILES" ]
-then
-      echo "No md files changed"
-else
-    # Vale 
-      vale --config=./.vale.ini $DIFF_FILES
+if ! command -v vale &> /dev/null; then
+  echo "vale could not be found."
+  echo "Please make sure it is installed on your system: https://docs.errata.ai/vale/install"
+  exit 1
 fi
 
+npx lint-staged
